ASA_2531 Integration with Appscan SDK
hclproducts/appscan-bamboo-plugin pull request #5
Opened 2020-10-22 15:53 UTC by tanmoyguha-hcl

Integrating Bamboo Plugin with Appscan SDK

2020-10-27 21:01 UTC, mattmurp requested changes

2020-10-27 21:01 UTC, mattmurp commented on src/main/java/com/hcl/appscan/bamboo/plugin/auth/BambooAuthenticationProvider.java
> +		return SystemUtil.getDefaultServer();
This should call `SystemUtil.getServer(userName)` in order to support different regions.

2020-10-27 21:01 UTC, mattmurp commented on src/main/java/com/hcl/appscan/bamboo/plugin/impl/ASoCDASTScanner.java
> +		} catch (Exception e) {
Can you catch the specific exception types that may be thrown rather than Exception?

2020-10-27 21:01 UTC, mattmurp commented on src/main/java/com/hcl/appscan/bamboo/plugin/impl/ASoCDASTScanner.java
> +	public File initWorkingDir(TaskContext taskContext) throws TaskException {
How does the working directory relate to a DAST scan?  Is this method really needed?

2020-10-27 21:01 UTC, mattmurp commented on src/main/java/com/hcl/appscan/bamboo/plugin/impl/ISASTConstants.java
> +
Many of these constants are DAST specific, so it would be best to rename the interface.  Also, many of them are already defined in the appscan-sdk, so we should use what's there and only add any additional constants that are specific to Bamboo.

2020-10-27 21:01 UTC, mattmurp commented on src/main/java/com/hcl/appscan/bamboo/plugin/impl/SASTScanTaskConfigurator.java
>  public class SASTScanTaskConfigurator extends AbstractTaskConfigurator implements TaskRequirementSupport, ISASTConstants {
It looks like this class is used for both SAST and DAST scans, so can you update the name to remove SAST?

2020-10-27 21:01 UTC, mattmurp commented on src/main/java/com/hcl/appscan/bamboo/plugin/impl/ScannerTask.java
> +	private void setUsernameAndPassword(TaskContext taskContext) {
Rather than storing the credentials in plain text in memory (i.e. as Strings in the AbstractASoCScanner class) can you instead pass the Credentials object, which I assume at a minimum masks the values?  And then the user name and password can simply be retrieved from the Credentials object only when they are needed.

2020-10-28 11:25 UTC, tanmoyguha-hcl commented on src/main/java/com/hcl/appscan/bamboo/plugin/impl/ASoCDASTScanner.java
> +		} catch (Exception e) {
I have updated the code to handle only specific exceptions ScannerException and InvalidTargetException.

2020-10-28 11:29 UTC, tanmoyguha-hcl commented on src/main/java/com/hcl/appscan/bamboo/plugin/impl/ASoCDASTScanner.java
> +	public File initWorkingDir(TaskContext taskContext) throws TaskException {
Actually this directory is recreated everytime a new build is triggered and acts as working directory, so report is first downloaded in this folder and then attached to the build.

2020-10-28 11:31 UTC, tanmoyguha-hcl commented on src/main/java/com/hcl/appscan/bamboo/plugin/impl/SASTScanTaskConfigurator.java
>  public class SASTScanTaskConfigurator extends AbstractTaskConfigurator implements TaskRequirementSupport, ISASTConstants {
renamed it to ScanTaskConfigurator

2020-10-28 11:36 UTC, tanmoyguha-hcl commented on src/main/java/com/hcl/appscan/bamboo/plugin/impl/ScannerTask.java
> +	private void setUsernameAndPassword(TaskContext taskContext) {
Updated the code to have Credentials object rather than Username and Password.

2020-10-28 12:30 UTC, tanmoyguha-hcl commented on src/main/java/com/hcl/appscan/bamboo/plugin/auth/BambooAuthenticationProvider.java
> +		return SystemUtil.getDefaultServer();
Updated the code to use SystemUtil.getServer(userName)

2021-02-02 09:08 UTC, knowds approved these changes

2021-03-05 12:42 UTC, mattmurp approved these changes

2021-03-05 12:42 UTC, mattmurp commented on src/main/java/com/hcl/appscan/bamboo/plugin/impl/ASoCSASTScanner.java
> +		} catch (InvalidTargetException e) {
Since we're handling both exception in the same way, I would suggest combining the 2 exceptions into 1 catch, e.g. 
`catch (ScannerException | InvalidTargetException e)`

2021-03-05 12:42 UTC, merged